language: python

python:
  - "3.6"

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE django_dungeonbot_db;" -U postgres

script: cd dungeonbot && make test
